options:
    formatter: stylish
files:
    include: 'src/scss/**/*.scss'
    ignore:
        - 'src/scss/mixins/**/*.scss'
        - 'src/scss/vendor/**/*.scss'
rules:
    indentation:
        - 1
        -
            size: 4
